### ISSUE TITLE
Ability to Add User @ Mentions in addition to Email address

### ISSUE THREAD

**Issue by arjs1000** [DoodleScheduling/android-material-chips#10]
Hi there, 

I am developing with this library and found the need to extend it to support @ mentions in addition to email addresses. I aim to add the flexibility to use custom regex patterns too. 

Please let me know if this is something you are currently working on. 

Otherwise, expect a pull request with these improvements soon.

Arjun

**Comment by myacxy** [comment]
Hey @arjs1000,
we do not have any plans to deviate from the current `Contact` model. However, you are more than welcome to file a pull request as soon as you are ready or ask for any help along the way.
