### ISSUE TITLE
Text and Chips are not at the same level

### ISSUE THREAD

**Issue by neokree** [DoodleScheduling/android-material-chips#11]
When you add an email manually, the cursor is not at the same level of the chips but it is under that. 
This cause to have a bigger view when it's not necessary.

For example if I want to have a 56dp height chipsView and I set `android:minHeight="56dp"` the cursor is in the correct position, but the chips haven't a padding from the top. 
Adding a paddingTop to the view cause the view to have a greater height, so it's not correct again.

Following the material design specs, the cursor shold be at the same level of the chips.
<img src="http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7aF92ZTRxOTU4U00/components_chips_contact1.png">

**Comment by AlexanderThiele** [comment]
Hey @neokree, we just released a new version (1.1.0) where we fixed your issue. Could you please check out the latest version and let me know if everything works?

**Comment by neokree** [comment]
yes in the 1.1.0 version this issue is fixed
