### ISSUE TITLE
Provide a hint text like EditText

### ISSUE THREAD

**Issue by PravSonawane** [DoodleScheduling/android-material-chips#14]
Hi,
Great library.
It would be nice to have the ability to provide a hint text just like EditText.

Thanks
Pravin

**Comment by SouhaibGuitouni** [comment]
Hello,
  Good jog! Will there be a release with the hints? (Release 1.1.0 doesn't inculde the fix).

**Comment by PravSonawane** [comment]
Hi
It seems they haven't merged this pull request yet.

Thanks
Pravin
