### ISSUE TITLE
How to make the chipview non-editable?

### ISSUE THREAD

**Issue by delstra** [DoodleScheduling/android-material-chips#2]
Heyy thanks a lot for this library it is awesome. Can you help me out to make the chipview non editable. I just want to display the chips.

**Comment by AlexanderThiele** [comment]
Hey @delstra,
you can add a flag to disable editing for single chips.
```mChipsView.addChip(email, imgUrl, contact, true);```

it's not yet possible to disable the whole ChipsView but i just found a workaround. 
Create a new class in your project and extend the ChipsView class. Override `onInterceptTouchEvent(MotionEvent ev)` and return true: 

```java
public class MyChipsView extends ChipsView {
    public MyChipsView(Context context) {
        super(context);
    }

    public MyChipsView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public MyChipsView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    public MyChipsView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return true;
    }
}
```

Then use your class in your layout file. 

```xml
<your.package.name.MyChipsView
            android:id="@+id/chipsView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />
```

**Comment by delstra** [comment]
hey thanks a lot that works well. can u help to disable the cursor on the edittext of chipview. @AlexanderThiele

**Comment by AlexanderThiele** [comment]
Hey @delstra, I can add this feature in the next version. 

But for now (a workaround again^^) you have to search for the editText view because it's not yet reachable from outside. 

something like:
```java
        EditText editText = null;
        for (int i = 0; i < mChipsView.getChildCount(); i++) {
            if(mChipsView.getChildAt(i) instanceof EditText){
                editText = (EditText) mChipsView.getChildAt(i);
            }
        }
        if(editText != null){
            // do whatever you want to do with this EditText
            editText.setCursorVisible(false);
        }
```

**Comment by delstra** [comment]
hey @AlexanderThiele thanks a lot. :-)

**Comment by dilipbirajadar** [comment]
I have same issue not working for me...                                                                                              
           EditText editText = null;
                for (int k = 0; k < mChipsView.getChildCount(); k++) {
                    if(mChipsView.getChildAt(i) instanceof EditText){
                        editText = (EditText) mChipsView.getChildAt(k);
                    }
                }
                if(editText != null){
                    // do whatever you want to do with this EditText
                    editText.setCursorVisible(false);
                    editText.setEnabled(false);
                }
