### ISSUE TITLE
check boxes and chips are not synchronized 

### ISSUE THREAD

**Issue by omidaminiva** [DoodleScheduling/android-material-chips#24]
If add a user by checking a check box from list then delete that item from chipsview, in the list checkbox is still selected. Also if I add a user by typing it to chipsview in the list that user wont be selected.

**Comment by AndroidDeveloperLB** [comment]
True. It doesn't even have a set of the contacts that are supposed to be checked, so it can't be in sync.
Not only that, but "getItemViewType" returns a new view type for each item in the list, so it creates a new view per item...
Whoever did this, used too many workaround just to make it look as if it works fine...
It needs more work...

**Comment by AlexanderThiele** [comment]
Hey @omidaminiva and @AndroidDeveloperLB are you talking about the sample implementation? because the sample is not perfect right now and should just show the basic usage. If you want, you can improve the sample and create a pull request :)

**Comment by AndroidDeveloperLB** [comment]
It's not just that it lacks features. It is buggy.
