### ISSUE TITLE
ChipsEmailDialogFragment and orientation changes

### ISSUE THREAD

**Issue by dbarwacz** [DoodleScheduling/android-material-chips#25]
`ChipsEmailDialogFragment` has `set*Listener` methods. Due to the nature of fragment->activity interaction, if not cleared manually, those become view leak after activity is recreated. What is more, newly (re)created fragment won't work because nobody called `set*Listener` on it. 

I think there are to possible solutions as follow: 
- either use local broadcast manager to communicate dialog->view,
- require chip view host to implement callback and be responsible for forwarding that call to chipview.

I would go for the first and I can prepare fix if you agree on the issue and suggested fix.

**Comment by AlexanderThiele** [comment]
Hey, sorry for the late reply.
i removed the dialog completely. you can now show your own dialog instead.
