### ISSUE TITLE
Unable to resolve dependency - Maven Central

### ISSUE THREAD

**Issue by jlindenbaum** [DoodleScheduling/android-material-chips#3]
Searching the maven central repository, I can't seem to find the project. Is it hosted on a different repository?

`http://search.maven.org/#search%7Cga%7C1%7Ccom.doodle.android` yields no results, and my gradle can't resolve the dependency to build my project.

**Comment by AlexanderThiele** [comment]
Hi @jlindenbaum the library is only on jcenter (for now). https://jcenter.bintray.com/com/doodle/android/

You can add jcenter to your gradle project with:

```
buildscript {
    repositories {
        jcenter()
    }
}
```

**Comment by jlindenbaum** [comment]
Thank you! I must've missed that in the read me. 






On Tue, Mar 1, 2016 at 12:19 AM -0800, "Alexander" <notifications@github.com> wrote:












Hi @jlindenbaum the library is only on jcenter (for now). https://jcenter.bintray.com/com/doodle/android/



You can add jcenter to your gradle project with:

buildscript {
    repositories {
        jcenter()
    }
}
